(library (lib randomness)
  (export std-normal normal std-uniform uniform)
  (import (chezscheme)
	  (lib constants))
  (begin
    (define (std-normal)
      (* (sqrt (* -2.0 (log (random 1.0))))
	 (cos (* 2 pi (random 1.0)))))
    (define (normal m s)
      (+ m (* (std-normal) s)))
    (define (std-uniform)
      (random 1.0))
    (define (uniform min max)
      (+ min (* (std-uniform) (- max min))))))
